In [1]:
import numpy as np 
import time 

In [2]:
#create - from list 
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype ,arr.shape)

arr2=np.array([1,2,4,"string"]) 
print(arr2,type(arr2),arr2.dtype , arr.shape)

arr2d = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(arr2d , arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '4' 'string'] <class 'numpy.ndarray'> <U21 (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [3]:
#create 
arr1=np.zeros((2,3), dtype="int64") #prefill
print(arr1 , arr1.shape)

arr2=np.ones((5, ), dtype="int64") #prefill
print(arr2 , arr2.shape)

arr3=np.full((3,4), 100 ,  dtype="int64") #prefill with values
print(arr3 , arr3.shape)

arr4=np.eye((3), dtype="int64") #identity matrix
print(arr4 , arr4.shape)

arr5=np.arange(1,11,2) # range elements
print(arr5 , arr5.shape)

arr6=np.linspace(1,100,4) #evenly spaced arrays
print(arr6 , arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [4]:
#Operations on array 

arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened = arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [5]:
#indexing 
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0][2])

#fancy indexing 

arr2=np.array([1,2,3,4,5,6,7,8])

idx=[0,1,3]
print(arr2[idx])

#Boolean Indexing 

arr3=np.array([1,2,3,4,5,6,7,8])
print(arr3[arr3>2])
print(arr3 % 2 == 0 )


3
[1 2 4]
[3 4 5 6 7 8]
[False  True False  True False  True False  True]


In [6]:
#Slicing 

arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5 6 7 8]
[1 2 3 4]
[1 3 5 7]


In [7]:
# Copy Vs View 

nums = [1,2,3,4,5,6,7,8]
sub_list = nums[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(nums)

arr=np.array([1,2,3,4,5,6,7,8])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5, 6, 7, 8]
[2 3]
[200   3]
[  1 200   3   4   5   6   7   8]


In [8]:
#Data Types 
arr=np.array([1,2,3.4,4,5,6])
print(arr,arr.dtype)

#complex number 
arr1=np.array([3+5j])
arr2=np.array([2+3j])

print(arr1 + arr2)
print(arr1 - arr2)

#String types
arr3=np.array(["prime",{1,2,3},3.14])
print(arr3,arr3.dtype)


[1.  2.  3.4 4.  5.  6. ] float64
[5.+8.j]
[1.+2.j]
['prime' {1, 2, 3} 3.14] object


In [9]:
#Multi-dimensional arrays

arr2d = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(arr2d , arr2d.ndim)

print(np.sum(arr2d))

sum_of_columns = np.sum(arr2d , axis = 0)
sum_of_rows = np.sum(arr2d , axis = 1)
print(sum_of_columns)
print(sum_of_rows)

print(arr2d[0:2,1:2])

                      

[[1 2 3]
 [4 5 6]
 [7 8 9]] 2
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [10]:
#3D array 
arr3D=np.array([[[1,2] , [3,4] , [5,6]] , [[7,8] , [9,10] , [11,12]]])
print(arr3D , arr3D.shape )

#Indexing
print(arr3D[1,2,1])

#Slicing 
print(arr3D[:,0,:])
print(arr3D[:,:,0])

#replace 
arr3D[:,0,:]=99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
12
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [11]:
# Vectorization 

arr= np.array([1,2,3,4,5])
print(arr ** 2)
print (arr + 10 )

[ 1  4  9 16 25]
[11 12 13 14 15]


In [12]:
#broadcasting 
arr= np.array([1,2,3,4,5])
arr2= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr+arr2)

[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [13]:
# normalization 

arr=np.array([[1,2] , [3,4]])
mean = np.mean(arr)
std = np.std(arr)

normalized_arr=(arr-mean)/std
print(normalized_arr)

mean1=np.mean(normalized_arr)
std1=np.std(normalized_arr)
print(mean1)
print(std1)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
0.0
1.0


In [14]:
#aggregation 

arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))



15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [15]:
#Power Function 
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [16]:
#log

arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [17]:
#rounding

print(np.round(3.14))
print(np.round(3.67))
print(np.ceil(3.67))
print(np.floor(3.67))
print(np.trunc(3.67))
arr=np.array([1,2,5,1,4,3,4,5])
print(np.unique(arr))
print(np.sort(arr))
arr1=np.array([1,-2,5,-1,-4,3,4,5])
print(np.abs(arr1))

3.0
4.0
4.0
3.0
3.0
[1 2 3 4 5]
[1 1 2 3 4 4 5 5]
[1 2 5 1 4 3 4 5]
